### ISSUE TITLE
Add Faction Exclusion field

### ISSUE THREAD

**Issue by bloodydoves** [IceRaptor/ConcreteJungle#6]
I'm a monster but here's one more request that's hopefully not too rough.

I'd like the option in CJ's settings to set a faction exclusion so that certain factions can be defined as *not* spawning ambushes. Specifically this applies because the Clans are unlikely to hide tanks inside of buildings to ambush you. This is pretty low priority but worth asking in case it's fairly easy to achieve.

**Comment by IceRaptor** [comment]
Added in 2.1.0
